### ISSUE TITLE
Heart counter does not go up

### ISSUE THREAD

**Issue by MathewKJ2048** [gladly-team/tab-extensions#50]
When I installed the extension on the latest version of microsoft edge and opened 2 new tabs, the heart counter stayed the same

**Comment by kmjennison** [comment]
Hi, thanks for the issue! Sometimes, the hearts won't increase because tabs are opened too quickly. We rate-limit hearts to prevent tab-spamming, which can be counterproductive to our goal of raising money for great causes.

If your hearts _never_ increase, that's definitely a problem. Get in touch at contact@tabforacause.org, and we'll help ASAP.
